const pictures_recipes = [
    "./Recipes pictures/Pizza Margherita.jpeg",
    "./Recipes pictures/Vegetarian Stir-Fry.jpeg",
    "./Recipes pictures/Chocolate Chip Cookies.jpeg",
    "./Recipes pictures/Chicken Alfredo Pasta.jpeg",
    "./Recipes pictures/Mango Salsa Chicken.jpeg",
    "./Recipes pictures/Quinoa Salad with Avocado.jpeg",
    "./Recipes pictures/Tomato Basil Bruschetta.jpeg",
    "./Recipes pictures/Beef and Broccoli Stir-Fry.jpeg",
    "./Recipes pictures/Caprese Salad.jpeg",
    "./Recipes pictures/Shrimp Scampi Pasta.jpeg",
    "./Recipes pictures/Chicken Biryani.jpeg",
    "./Recipes pictures/Chicken Karahi.jpeg",
    "./Recipes pictures/Aloo Keema.jpeg",
    "./Recipes pictures/Chapli Kebabs.jpeg",
    "./Recipes pictures/Saag (Spinach) with Makki di Roti.jpeg",
    "./Recipes pictures/Japanese Ramen Soup.jpeg",
    "./Recipes pictures/Moroccan Chickpea Tagine.jpeg",
    "./Recipes pictures/Korean Bibimbap.jpeg",
    "./Recipes pictures/Greek Moussaka.jpeg",
    "./Recipes pictures/Butter Chicken (Murgh Makhani).jpeg",
    "./Recipes pictures/Thai Green Curry.jpeg",
    "./Recipes pictures/Mango Lassi.jpeg",
    "./Recipes pictures/Italian Tiramisu.jpeg",
    "./Recipes pictures/Turkish Kebabs.jpeg",
    "./Recipes pictures/Blueberry Banana Smoothie.jpeg",
    "./Recipes pictures/Mexican Street Corn (Elote).jpeg",
    "./Recipes pictures/Russian Borscht.jpeg",
    "./Recipes pictures/South Indian Masala Dosa.jpeg",
    "./Recipes pictures/Lebanese Falafel Wrap.jpeg",
    "./Recipes pictures/Brazilian Caipirinha.jpeg"
]